// Generated by https://quicktype.io

export interface Pagination {
  start: number;
  limit: number;
  more_items_in_collection: boolean;
  next_start: number;
}

export interface AdditionalData {
  pagination: Pagination;
}

export interface ContactInfo {
  value: string;
  primary: boolean;
  label: string;
}

export interface OrgID {
  name: string;
  people_count: number;
  owner_id: number;
  address: string;
  active_flag: boolean;
  cc_email: string;
  value?: number;
  id?: number;
}

export interface OwnerID {
  id: number;
  name: string;
  email: string;
  has_pic: number;
  pic_hash: string;
  active_flag: boolean;
  value?: number;
}

export interface PictureID {
  item_type: string;
  item_id: number;
  active_flag: boolean;
  add_time: string;
  update_time: string;
  added_by_user_id: number;
  pictures: { [key: string]: string };
  value?: number;
  id?: number;
}

export interface Person {
  id: number;
  company_id: number;
  owner_id: OwnerID;
  org_id: OrgID;
  name: string;
  first_name: string;
  last_name: string;
  open_deals_count: number;
  related_open_deals_count: number;
  closed_deals_count: number;
  related_closed_deals_count: number;
  participant_open_deals_count: number;
  participant_closed_deals_count: number;
  email_messages_count: number;
  activities_count: number;
  done_activities_count: number;
  undone_activities_count: number;
  files_count: number;
  notes_count: number;
  followers_count: number;
  won_deals_count: number;
  related_won_deals_count: number;
  lost_deals_count: number;
  related_lost_deals_count: number;
  active_flag: boolean;
  phone: ContactInfo[];
  email: ContactInfo[];
  first_char: string;
  update_time: string;
  add_time: string;
  visible_to: string;
  marketing_status: string;
  picture_id: PictureID | null;
  next_activity_date: string;
  next_activity_time: string;
  next_activity_id: number;
  last_activity_id: number;
  last_activity_date: string;
  last_incoming_mail_time: string;
  last_outgoing_mail_time: string;
  label: number;
  org_name: string;
  owner_name: string;
  cc_email: string;
  '73d17c3f4d3c8a3856179466873d81a19b931b68': string;
  a4329aa33eb3484ce969c8ea9955d7c6a3d2b954: string;
}

export interface PersonsResponse {
  success: boolean;
  data: Person[];
  additional_data: AdditionalData;
  related_objects: Record<string, object>;
}

export interface Items {
  result_score: number;
  item: Person;
}

export interface PersonsSearchResponse {
  success: boolean;
  data: { items: Items[] };
  additional_data: AdditionalData;
}

export interface PersonByIdResponse {
  success: boolean;
  data: Person;
  additional_data: AdditionalData;
  related_objects: Record<string, object>;
}

export interface DeletePersonResponse {
  success: boolean;
  data: { id: number };
}

export interface CreatePersonRequest {
  name: string;
  email?: ContactInfo[];
  phone?: ContactInfo[];
  '73d17c3f4d3c8a3856179466873d81a19b931b68'?: string;
  a4329aa33eb3484ce969c8ea9955d7c6a3d2b954?: string;
}
